[workspace]
resolver = "2"
exclude = ["example"]
members = ["capnp_conv", "capnp_conv_macros", "capnp_conv_tests"]

[workspace.package]
edition = "2018"
license = "MIT"
repository = "https://github.com/aikalant/capnp_conv"
rust-version = "1.66"

[workspace.dependencies]
capnp = "0.14"
capnpc = "0.14"
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
