imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Unix"
edition = "2021"
tab_spaces = 4
use_try_shorthand = true
use_field_init_shorthand = true
force_multiline_blocks = false
